### ISSUE TITLE
Issue with the Background Colour

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/kraken-good-accessibility#1]
Hi @hellachella and @jessjodoin,

I'm having an issue with the background-colour when I run the assignment through Markbot (screenshot attached).

By comparing my website with the screenshot provided, visually they look the same to me. Is there some accessibility tool in the browser that I can use to locate the issue with the background?

Thanks,
Rianna

<img width="495" alt="Screen Shot 2020-10-02 at 1 28 31 PM" src="https://user-images.githubusercontent.com/55094049/94951984-346abe80-04b3-11eb-8004-c2510e48bb7b.png">

**Comment by JessJodoin** [comment]
Add this background-color to your header

` background-color: #1e7c74;`

**Comment by JessJodoin** [comment]
Also add it to the footer as well

**Comment by riannazandbelt** [comment]
Great, thanks! I had just re-read the Markbot message and finally clued in to what it was referring to

**Comment by JessJodoin** [comment]
No worries!
